---
- hosts: all
  handlers:
    - name: Reinicia Apache
      service:
        name: apache2
        state: restarted
      become: yes
  tasks:
    - name: 'Instalando pacotes'
      apt:
        name: ['php7.4', 'apache2', 'libapache2-mod-php7.4','php7.4-gd','mysql-server','php7.4-mysql','python3-pymysql']
        state: latest
      become: yes

    - name: 'Criando o banco MySQL'
      mysql_db:
        name: "{{ wp_db }}"
        login_user: "{{ wp_user_db }}"
        login_password: "{{ wp_pass_db }}"
        state: present

    - name: 'Baixa o Wordpress(tar.gz)'
      get_url:
        url: https://br.wordpress.org/latest-pt_BR.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: 'Descompacta Wordpress'
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes
      become: yes

    - name: Trazendo configurção default do wordpress(host remoto)
      copy:
        src: "{{ wp_installation_dir }}/wp-config-sample.php"
        dest: "{{ wp_installation_dir }}/wp-config.php"
        remote_src: yes
      become: yes

    - name: Configurando o wp-config do wordpress
      replace:
        path: "{{ wp_installation_dir }}/wp-config.php"
        regexp: "{{item.regex}}"
        replace: '{{item.value}}'
        backup: yes
      loop:
        - { regex: 'nome_do_banco_de_dados_aqui', value: "{{ wp_db }}"}
        - { regex: 'nome_de_usuario_aqui', value: "{{ wp_user_db }}"}
        - { regex: 'senha_aqui', value: "{{ wp_pass_db }}" }
      become: yes

    - name: 'Configurando Apache para Wordpress'
      template:
        src: templates/000-default.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf
      become: yes
      notify:
        - Reinicia Apache